import os
import re
import importlib.util
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import spearmanr, ttest_rel

from loader import load_flight
from correlation import compute_delay_matrices
from analysis import compute_ti_ranking


DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# Minimum mean C_max for a flight to be included in cross-flight analysis
QUALITY_THRESHOLD = 0.5


def load_data_module(path: str) -> dict:
    """
    Load a generated flight data module by file path.

    Parameters
    ----------
    path : str
        Absolute path to a _data.py file generated by generate_all_data.py.

    Returns
    -------
    dict : bird_id -> list of rows
    """
    spec = importlib.util.spec_from_file_location("flight_data", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return getattr(mod, "data")


def run_pipeline(data: dict) -> dict | None:
    """
    Run the full analysis pipeline on a single flight.

    Loads flight data, computes delay matrices, checks flight quality
    against QUALITY_THRESHOLD, and returns the hierarchy analysis.
    Flights with mean C_max below the threshold are excluded as their
    directional correlations are too weak to produce reliable hierarchies.

    Parameters
    ----------
    data : dict
        Raw flight data as produced by generate_all_data.py.

    Returns
    -------
    dict from compute_ti_ranking, or None if the flight fails quality check.
    """
    try:
        t_seconds, pos_xy, vel_xy, valid_mask = load_flight(data)
        result = compute_delay_matrices(
            t_seconds=t_seconds,
            pos_xy=pos_xy,
            vel_xy=vel_xy,
            valid_mask=valid_mask,
            tau_min=-1.0,
            tau_max=1.0,
            min_points_per_tau=20,
        )

        c_vals = result.c_max[~np.isnan(result.c_max)]
        mean_c = float(np.mean(c_vals)) if len(c_vals) > 0 else 0.0
        print(f"  Mean C_max: {mean_c:.3f}", end="")

        if mean_c < QUALITY_THRESHOLD:
            print(" — below quality threshold, skipping")
            return None

        print()
        return compute_ti_ranking(result, c_min=0.5)

    except Exception as e:
        print(f"  Pipeline error: {e}")
        return None


def compare_rankings(analysis_a: dict, analysis_b: dict) -> tuple | None:
    """
    Compute Spearman rank correlation of t_i values for birds common to both flights.

    Parameters
    ----------
    analysis_a, analysis_b : dicts from compute_ti_ranking

    Returns
    -------
    (r, p, n_common) or None if fewer than 3 common birds with valid t_i values.
    """
    common = sorted(set(analysis_a["ti"]) & set(analysis_b["ti"]))
    if len(common) < 3:
        return None

    ti_a = np.array([analysis_a["ti"][b] for b in common])
    ti_b = np.array([analysis_b["ti"][b] for b in common])

    mask = ~(np.isnan(ti_a) | np.isnan(ti_b))
    if mask.sum() < 3:
        return None

    r, p = spearmanr(ti_a[mask], ti_b[mask])
    return r, p, int(mask.sum())


def bootstrap_correlation(ti_a: np.ndarray, ti_b: np.ndarray,
                          n_boot: int = 1000, ci: float = 0.95) -> tuple:
    """
    Bootstrap confidence interval for Spearman correlation.

    Resamples pairs with replacement to estimate the sampling distribution
    of the correlation coefficient. Addresses the small sample size problem
    (typically n=7-9 birds) by providing uncertainty bounds rather than
    relying on p-values alone.

    Parameters
    ----------
    ti_a, ti_b : matched t_i arrays for two flights
    n_boot     : number of bootstrap resamples
    ci         : confidence level (default 0.95 for 95% CI)

    Returns
    -------
    (lower, upper) confidence interval bounds
    """
    rng = np.random.default_rng(42)
    n = len(ti_a)
    boot_r = np.empty(n_boot)

    for i in range(n_boot):
        idx = rng.integers(0, n, size=n)
        a_sample = ti_a[idx]
        b_sample = ti_b[idx]
        # Skip if either resampled array is constant — spearman undefined
        if np.all(a_sample == a_sample[0]) or np.all(b_sample == b_sample[0]):
            boot_r[i] = 0.0
            continue
        r, _ = spearmanr(a_sample, b_sample)
        boot_r[i] = r if not np.isnan(r) else 0.0 # type: ignore

    alpha = (1 - ci) / 2
    return float(np.quantile(boot_r, alpha)), float(np.quantile(boot_r, 1 - alpha))


def paired_free_vs_homing(results: dict) -> None:
    """
    Paired t-test comparing t_i values between free and homing flights.

    For each bird that appears in at least one free flight and one homing
    flight, computes its mean t_i across each flight type and tests whether
    the difference is significant. Directly addresses the brief's question
    of whether coordination rules differ between flight contexts.

    Parameters
    ----------
    results : dict flight_name -> analysis dict from compute_ti_ranking
    """
    free_flights   = [f for f in results if f.startswith("ff")]
    homing_flights = [f for f in results if f.startswith("hf")]

    if not free_flights or not homing_flights:
        print("\nNot enough flight types for paired t-test")
        return

    all_birds = sorted(set(b for f in results for b in results[f]["ti"]))
    free_ti   = []
    homing_ti = []
    birds_used = []

    for bird in all_birds:
        ff_vals = [results[f]["ti"][bird] for f in free_flights
                   if bird in results[f]["ti"]
                   and not np.isnan(results[f]["ti"][bird])]
        hf_vals = [results[f]["ti"][bird] for f in homing_flights
                   if bird in results[f]["ti"]
                   and not np.isnan(results[f]["ti"][bird])]

        if ff_vals and hf_vals:
            free_ti.append(np.mean(ff_vals))
            homing_ti.append(np.mean(hf_vals))
            birds_used.append(bird)

    if len(birds_used) < 3:
        print("\nNot enough common birds for paired t-test")
        return

    free_ti   = np.array(free_ti)
    homing_ti = np.array(homing_ti)
    t_stat, p_val = ttest_rel(free_ti, homing_ti)

    print("\n--- Paired t-test: free vs homing flight t_i ---")
    print(f"  Birds: {birds_used}")
    print(f"  Mean t_i free flights:   {free_ti.mean():+.3f}s")
    print(f"  Mean t_i homing flights: {homing_ti.mean():+.3f}s")
    print(f"  t = {t_stat:.3f}, p = {p_val:.3f}")
    if p_val < 0.05:
        print("  Significant difference between flight types")
    else:
        print("  No significant difference between flight types")


if __name__ == "__main__":
    data_files = sorted([
        f for f in os.listdir(DATA_DIR)
        if re.match(r"(ff|hf)\d+_data\.py$", f)
    ])

    print(f"Found {len(data_files)} flight data files\n")

    results = {}
    for fname in data_files:
        flight_name = fname.replace("_data.py", "")
        print(f"Processing {flight_name}...")
        flight_data = load_data_module(os.path.join(DATA_DIR, fname))
        analysis = run_pipeline(flight_data)
        if analysis:
            results[flight_name] = analysis
            ranking_str = " > ".join(b for b, _ in analysis["ranking"])
            print(f"  Hierarchy: {ranking_str}")
        else:
            print("  Failed — skipping")

    # t_i table
    all_birds = sorted(set(b for a in results.values() for b in a["ti"]))
    flights   = sorted(results.keys())

    print("\n--- t_i values across flights ---")
    header = f"{'Bird':<6}" + "".join(f"{f:>10}" for f in flights)
    print(header)
    print("-" * len(header))
    for bird in all_birds:
        row = f"{bird:<6}"
        for flight in flights:
            ti = results[flight]["ti"].get(bird, float("nan"))
            row += f"{ti:>+10.3f}" if not np.isnan(ti) else f"{'---':>10}"
        print(row)

    # Pairwise Spearman correlations with bootstrap CIs
    print("\n--- Pairwise ranking correlation (Spearman r) ---")
    for idx_a, fa in enumerate(flights):
        for fb in flights[idx_a + 1:]:
            out = compare_rankings(results[fa], results[fb])
            if out:
                r, p, n = out
                common = sorted(set(results[fa]["ti"]) & set(results[fb]["ti"]))
                ti_a   = np.array([results[fa]["ti"][b] for b in common])
                ti_b   = np.array([results[fb]["ti"][b] for b in common])
                mask   = ~(np.isnan(ti_a) | np.isnan(ti_b))
                lo, hi = bootstrap_correlation(ti_a[mask], ti_b[mask])
                sig    = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
                print(f"  {fa} vs {fb}: r={r:+.3f}, p={p:.3f}, "
                      f"95% CI [{lo:+.3f}, {hi:+.3f}], n={n} {sig}")

    # Heatmap
    ti_matrix = np.full((len(all_birds), len(flights)), np.nan)
    for j, flight in enumerate(flights):
        for i, bird in enumerate(all_birds):
            ti_matrix[i, j] = results[flight]["ti"].get(bird, np.nan)

    fig, ax = plt.subplots(figsize=(14, 6))
    im = ax.imshow(ti_matrix, cmap="RdYlGn", aspect="auto",
                   vmin=np.nanmin(ti_matrix), vmax=np.nanmax(ti_matrix))
    ax.set_xticks(range(len(flights)))
    ax.set_xticklabels(flights, rotation=45, ha="right")
    ax.set_yticks(range(len(all_birds)))
    ax.set_yticklabels(all_birds)
    ax.set_xlabel("Flight")
    ax.set_ylabel("Bird")
    ax.set_title("t_i values across all flights\n"
                 "(green = leader, red = follower, white = not present)")

    for i in range(len(all_birds)):
        for j in range(len(flights)):
            val = ti_matrix[i, j]
            if not np.isnan(val):
                ax.text(j, i, f"{val:+.2f}", ha="center", va="center", fontsize=6)

    plt.colorbar(im, ax=ax, label="t_i (s)")
    plt.tight_layout()
    plt.savefig("cross_flight_heatmap.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("\nSaved: cross_flight_heatmap.png")

    paired_free_vs_homing(results)